### ISSUE TITLE
CAIQ 3.0.1 2017 version is newer than 2016, but generating 3.0.1 gives 2016 version

### ISSUE THREAD

**Issue by kwkwan** [metanorma/csa-ccm-tools#10]
![image](https://user-images.githubusercontent.com/29566367/61424363-c1c10200-a945-11e9-8fdb-e0ae815c0cba.png)

The sorting order is incorrect.  Version 2017 should be lower than version 2016. Please see the attached file.

Either the code should know which file is the latest release of the version, or the implied sorting order should be fixed (by renaming the files to adhere to the date order).

**Comment by CAMOBAP** [comment]
@ronaldtse I think better to fix this in code, and not really on lexicographical order

BTW @ronaldtse @kwkwan is there a guarantee that filename will always have format `csa-caiq-v{version}-{mm-dd-yyyy}`?

**Comment by ronaldtse** [comment]
@camobap795 the file name for files here (inside the gem) is up to us, so we can fix the order. However, I agree that it is better fixed in code using some attribute of the Excel file. Maybe we do both.

**Comment by ronaldtse** [comment]
Should have  been fixed in #14

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you please add a spec for this?

**Comment by ronaldtse** [comment]
I believe this is fixed.
